### ISSUE TITLE
Add API to entrypoint to expose deletion time

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/github-actions-controller#21]
## What

Add API to entrypoint to expose deletion time.
And fix pod sweeper.

## How

1. Remove RBAC for runner pods.
https://github.com/cybozu-go/github-actions-controller/blob/58d9042f99d643f3e7af18a59afc62d5de6f53bd/config/samples/manifests.yaml#L21-L52
2. Add API to entrypoint to expose deletion time and remove [this logic](https://github.com/cybozu-go/github-actions-controller/blob/58d9042f99d643f3e7af18a59afc62d5de6f53bd/cmd/entrypoint/cmd/root.go#L83-L86).
3. Fix the pod sweeper.
4. Fix runner pool reconciler. 
https://github.com/cybozu-go/github-actions-controller/blob/af39f46e3f0f19e76b89b9a26f695cc45b6f9a3a/controllers/runnerpool_controller.go#L180

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by kmdkuk** [comment]
If it returns an error before specifying the time to delete the Pod, the Pod will be restarted.
At this time, if the GitHub registration token has expired, it cannot be registered as a runner and the restart is repeated.
https://github.com/cybozu-go/github-actions-controller/blob/b8d1471a9c356ecbb997fd9bfe6b94fcd6a5220c/cmd/entrypoint/cmd/root.go#L74
https://github.com/cybozu-go/github-actions-controller/blob/b8d1471a9c356ecbb997fd9bfe6b94fcd6a5220c/cmd/entrypoint/cmd/root.go#L79

Set the deletion time before returning an error.
